# Generated by Django 4.2.5 on 2023-11-04 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_given_name_customer_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='id',
        ),
    ]
