# Generated by Django 4.2.5 on 2023-11-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_sku_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.CharField(max_length=300),
        ),
    ]
