# Generated by Django 5.0.1 on 2024-01-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
