# Generated by Django 5.0.1 on 2024-01-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_poductimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PoductImage',
            new_name='ProductImage',
        ),
    ]
